/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import ControlNavegacion.controlApp;
import DTO.CuentaDTO;

/**
 *
 * @author HP
 */
public class EditarPerfil extends javax.swing.JPanel {
    private controlApp control;
    /**
     * Creates new form EditarPerfil
     */
    public EditarPerfil(controlApp control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoNuevaContra = new javax.swing.JTextField();
        campoNuevoCorreoE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoNuevoNombre = new javax.swing.JTextField();
        BtnCancelar = new javax.swing.JButton();
        BtnAceptar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboDominio = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nuevco Correo Electronico");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        campoNuevaContra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(campoNuevaContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 230, 40));

        campoNuevoCorreoE.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(campoNuevoCorreoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 230, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Nuevo Nombre de Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Contrasenha");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        campoNuevoNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(campoNuevoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 230, 40));

        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 100, 40));

        BtnAceptar.setBackground(new java.awt.Color(0, 0, 0));
        BtnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAceptar.setText("Continuar");
        BtnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAceptarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 560, 110, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setText("Editar Perfil");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        comboDominio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboDominio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@outlook.com", "@outlook.es", "@hotmail.com" }));
        jPanel1.add(comboDominio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 170, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1010, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAceptarMouseClicked
        // TODO add your handling code here:
        obtenerDatos();
        control.mostrarConfirmarCambios();
    }//GEN-LAST:event_BtnAceptarMouseClicked

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        // TODO add your handling code here:
        control.mostrarMenuPerfil();
    }//GEN-LAST:event_BtnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JTextField campoNuevaContra;
    private javax.swing.JTextField campoNuevoCorreoE;
    private javax.swing.JTextField campoNuevoNombre;
    private javax.swing.JComboBox<String> comboDominio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void obtenerDatos(){
        CuentaDTO cuenta = control.obtenerCuenta();
        String nuevoNombre = campoNuevoNombre.getText();
        String nuevaContra = campoNuevaContra.getText();
        String nuevoCorre = campoNuevoCorreoE.getText() + comboDominio.getSelectedItem().toString();
        cuenta.setContrasenha(nuevaContra);
        cuenta.setCorreoE(nuevoCorre);
        cuenta.setNombreU(nuevoNombre);
        
    }

}
