/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;
import ControlNavegacion.controlApp;
import DTO.CuentaDTO;
/**
 *
 * @author HP
 */
public class Login extends javax.swing.JPanel {
    private controlApp control;
    /**
     * Creates new form Login
     */
    public Login(controlApp control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTItulo = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        BtnRegistro = new javax.swing.JButton();
        labelContra = new javax.swing.JLabel();
        campoContrasenha = new javax.swing.JTextField();
        campoCorreoE = new javax.swing.JTextField();
        labelCorreo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTItulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTItulo.setText("Bienvenido");
        add(labelTItulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        BtnLogin.setBackground(new java.awt.Color(102, 102, 102));
        BtnLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setText("Iniciar Sesion");
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLoginMouseClicked(evt);
            }
        });
        add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 380, 60));

        BtnRegistro.setBackground(new java.awt.Color(204, 204, 204));
        BtnRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnRegistro.setText("Registrarse");
        BtnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegistroMouseClicked(evt);
            }
        });
        add(BtnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 320, 60));

        labelContra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelContra.setText("Contrasenha");
        add(labelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));
        add(campoContrasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 360, 50));
        add(campoCorreoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 360, 50));

        labelCorreo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelCorreo.setText("Correo Electronico");
        add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistroMouseClicked
        // TODO add your handling code here:
        control.mostrarRegistro();
    }//GEN-LAST:event_BtnRegistroMouseClicked

    private void BtnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseClicked
        // TODO add your handling code here:
        validarCredenciales();
        //control.IniciarSesion()
    }//GEN-LAST:event_BtnLoginMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JTextField campoContrasenha;
    private javax.swing.JTextField campoCorreoE;
    private javax.swing.JLabel labelContra;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelTItulo;
    // End of variables declaration//GEN-END:variables

    private void validarCredenciales(){
        CuentaDTO cuenta = new CuentaDTO();
        cuenta.setCorreoE(campoCorreoE.getText());
        cuenta.setContrasenha(campoContrasenha.getText());
        control.setCuenta(cuenta);
        control.validarCredenciales();
    }
}
