/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import ControlNavegacion.controlApp;

/**
 *
 * @author HP
 */
public class MenuPrincipal extends javax.swing.JPanel {
    private controlApp control;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(controlApp control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnPerfil = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Biblioteca");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        BtnPerfil.setBackground(new java.awt.Color(51, 51, 51));
        BtnPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        BtnPerfil.setText("Perfil");
        add(BtnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPerfil;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
