/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import ControlNavegacion.controlApp;

/**
 *
 * @author HP
 */
public class Perfil extends javax.swing.JPanel {
    private controlApp control;
    /**
     * Creates new form Perfil
     */
    public Perfil(controlApp control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNombreU = new javax.swing.JLabel();
        panelImagenPerfil = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelInfoCuenta = new javax.swing.JPanel();
        campoCorreoE = new javax.swing.JLabel();
        labelInfo = new javax.swing.JLabel();
        campoContra = new javax.swing.JLabel();
        labelCorreoE1 = new javax.swing.JLabel();
        labelContra = new javax.swing.JLabel();
        BtnEditar = new javax.swing.JButton();
        campoBusqueda = new javax.swing.JTextField();
        BtnMenu = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombreU.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelNombreU.setText("nombre de usuario");
        jPanel1.add(labelNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        panelImagenPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(panelImagenPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 160, 150));

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelTitulo.setText("Mi perfil");
        jPanel1.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panelInfoCuenta.setBackground(new java.awt.Color(153, 153, 153));
        panelInfoCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoCorreoE.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoCorreoE.setText("Correo electronico:");
        panelInfoCuenta.add(campoCorreoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 300, -1));

        labelInfo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelInfo.setText("Informacion de la Cuenta");
        panelInfoCuenta.add(labelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        campoContra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoContra.setText("Correo electronico:");
        panelInfoCuenta.add(campoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        labelCorreoE1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelCorreoE1.setText("Correo electronico:");
        panelInfoCuenta.add(labelCorreoE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        labelContra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelContra.setText("Contrasenha:");
        panelInfoCuenta.add(labelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        BtnEditar.setBackground(new java.awt.Color(0, 0, 0));
        BtnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditar.setText("Editar");
        BtnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEditarMouseClicked(evt);
            }
        });
        panelInfoCuenta.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 110, 40));

        jPanel1.add(panelInfoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 720, 270));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 820, 630));

        campoBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campoBusqueda.setText("Busca una cancion, artista, album");
        add(campoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 460, 40));

        BtnMenu.setBackground(new java.awt.Color(0, 0, 0));
        BtnMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnMenu.setForeground(new java.awt.Color(255, 255, 255));
        BtnMenu.setText("Menu");
        BtnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMenuMouseClicked(evt);
            }
        });
        add(BtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEditarMouseClicked

    private void BtnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JLabel campoContra;
    private javax.swing.JLabel campoCorreoE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContra;
    private javax.swing.JLabel labelCorreoE1;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelNombreU;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelImagenPerfil;
    private javax.swing.JPanel panelInfoCuenta;
    // End of variables declaration//GEN-END:variables




}
