/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import ControlNavegacion.controlApp;
import DTO.CuentaDTO;

/**
 *
 * @author HP
 */
public class Registrarse extends javax.swing.JPanel {
    private controlApp control;
    /**
     * Creates new form Registrarse
     */
    public Registrarse(controlApp control) {
        this.control = control;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelCorreoE = new javax.swing.JLabel();
        labelContra = new javax.swing.JLabel();
        campoContrasenha = new javax.swing.JTextField();
        campoNombreU = new javax.swing.JTextField();
        campoCorreoE = new javax.swing.JTextField();
        comboDominioCorreo = new javax.swing.JComboBox<>();
        BtnContinuar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelTitulo.setText("Registrarse");
        add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 19, 290, -1));

        labelFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelFecha.setText("Fecha Nacimiento");
        add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelUsuario.setText("Nombre de Usuario");
        add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        labelCorreoE.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelCorreoE.setText("Correo Electronico");
        add(labelCorreoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        labelContra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelContra.setText("Contrasenha");
        add(labelContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));
        add(campoContrasenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 300, 50));
        add(campoNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 300, 50));
        add(campoCorreoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 300, 50));

        comboDominioCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboDominioCorreo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@gmail.com", "@outlook.com", "@outlook.es", "@hotmail.com" }));
        add(comboDominioCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 180, -1));

        BtnContinuar.setBackground(new java.awt.Color(51, 51, 51));
        BtnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        BtnContinuar.setText("Continuar");
        BtnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnContinuarMouseClicked(evt);
            }
        });
        add(BtnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 680, 160, 60));

        BtnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCancelar.setText("Cancelar");
        add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 160, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnContinuarMouseClicked
        // TODO add your handling code here:
            obtenerDatos();
            control.mostrarMenuPrincipal();
    }//GEN-LAST:event_BtnContinuarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnContinuar;
    private javax.swing.JTextField campoContrasenha;
    private javax.swing.JTextField campoCorreoE;
    private javax.swing.JTextField campoNombreU;
    private javax.swing.JComboBox<String> comboDominioCorreo;
    private javax.swing.JLabel labelContra;
    private javax.swing.JLabel labelCorreoE;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables

    public void obtenerDatos(){
        String nombreU = campoNombreU.getText();
        String correE = campoCorreoE.getText() + comboDominioCorreo.getSelectedItem().toString();
        String contra = campoContrasenha.getText();
        CuentaDTO cuenta = new CuentaDTO();
        cuenta.setNombreU(nombreU);
        cuenta.setCorreoE(correE);
        cuenta.setContrasenha(contra);
        
        System.out.println("Cuenta a agregar:  " + cuenta.toString());
        
    }

}
