/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import ControlNavegacion.controlApp;
import DTO.CuentaDTO;

/**
 *
 * @author HP
 */
public class ResumenCambios extends javax.swing.JPanel {
    private controlApp control;
    private CuentaDTO cuentaTemp;
    /**
     * Creates new form ResumenCambios
     */
    public ResumenCambios(controlApp control) {
        this.control = control;
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoNuevaContra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNuevoNombre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNuevoCorreo = new javax.swing.JLabel();
        BtnConfirmar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoNuevaContra.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoNuevaContra.setText("Nuevo nombre de usuario");
        jPanel1.add(campoNuevaContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Confirmar Cambios");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Nueva Contrasenha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Nuevo nombre de usuario:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        campoNuevoNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoNuevoNombre.setText("Nuevo nombre de usuario");
        jPanel1.add(campoNuevoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Nuevo Correo Electronico:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        campoNuevoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoNuevoCorreo.setText("Nuevo nombre de usuario");
        jPanel1.add(campoNuevoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        BtnConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        BtnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        BtnConfirmar.setText("Confirmar");
        BtnConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnConfirmarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, 130, 40));

        BtnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 130, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 67, 1010, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnConfirmarMouseClicked
        // TODO add your handling code here:
        control.confirmarCambios(cuentaTemp);
    }//GEN-LAST:event_BtnConfirmarMouseClicked

    private void BtnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCancelarMouseClicked
        // TODO add your handling code here:
        control.mostrarEditarPerfil();
    }//GEN-LAST:event_BtnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JLabel campoNuevaContra;
    private javax.swing.JLabel campoNuevoCorreo;
    private javax.swing.JLabel campoNuevoNombre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos(){
        cuentaTemp = control.obtenerCuentaEditada();
        //control.setCuenta(cuentaTemp)//CuentaDTO
        campoNuevoNombre.setText(cuentaTemp.getNombreU());
        campoNuevoCorreo.setText(cuentaTemp.getCorreoE());
        campoNuevaContra.setText(cuentaTemp.getContrasenha());
        
    }

}
